### ISSUE TITLE
IE Edge hangout with idletime set to 900

### ISSUE THREAD

**Issue by ajay-maurya** [LinearSoft/jquery-idleTimeout-plus#1]
Below is the configuration which has been set, however it hangs in IE Edge browser.

IdleTimeoutPlus.start({
                multiWindowSupport: true,
                idleTimeLimit: 900,
                bootstrap: false,
                warnTimeLimit: 60,
                redirectUrl: '<%= AppPath:~ %>' + '/app.axd/LogoutSession'
            });

Please help.

We are using JQuery 1.4.2 and modified your code: so instead of using $.now we are using (new Date).getTime(); and instead of .on we are using .live

**Comment by CrashSensei** [comment]
Have you used the src version of the plugin (src/jquery-idleTimeout-plus.js) this has debug info logged to the console. Try that and see if it helps narrow down where it is hanging.

**Comment by ajay-maurya** [comment]
Thanks for the guideline. looks like some IE Edge issue. I just checked it today again, and it is working fine. some MS - patches would have fixed some browser bug.
