### ISSUE TITLE
logoutAutoUrl is defaulted to string "null" instead of null. Prevents default logoutUrl being applied

### ISSUE THREAD

**Issue by rhetherington** [LinearSoft/jquery-idleTimeout-plus#4]
Firstly, thanks for the awesome plugin. After trying loads of different ones, yours by far works the best across multiple tabs, iframe popups and more.

In your source code you have wrongly configured the logoutAutoUrl. I believe it should be defaulted to null as a null and not a string value of "null". This is preventing the logoutUrl being copied to logoutAutoUrl

This Line
logoutAutoUrl: 'null', // URL for secondary tabs that received an automatic logout trigger (to help avoid race conditions)

Should be 
logoutAutoUrl: null, // URL for secondary tabs that received an automatic logout trigger (to help avoid race conditions)

In order for this line to correctly use the logoutUrl configured
if(config.logoutAutoUrl == null) config.logoutAutoUrl = config.logoutUrl;

Hope this helps.

Richard Hetherington

**Comment by FestiveNoodle** [comment]
Thanks! 
I noticed that too, did your change it fixed it. Now if I can figure out how to contribute to this project, we can have it fixed for everyone.

**Comment by rhetherington** [comment]
Yes, I simply replaced the "null" with null.

Regards,

Richard Hetherington

**Comment by bateller** [comment]
I submitted a PR to resolve this issue.

**Comment by CrashSensei** [comment]
PR integrated
